config/routes.rb
Food::Application.routes.draw do

  resources :fd_caixas do
    member do
      get :troca_caixa
    end
  end

  resources :fd_entregas
  match '/insere_entrega', to: 'fd_entregas#insere_entrega', via: 'get'
  

  resources :fd_pedidomistos

  resources :fd_situacoes

  resources :fd_produtotrocacombos

  resources :fd_pedidocombos

  resources :fd_produtocombos

  resources :fd_adicionaisinclusos

  resources :fd_itemalterados
  resources :fd_itempedidos
  resources :fd_pedidos
  resources :fd_categoriaprodutos

  resources :fd_produtos do
    member do
      get :show_service   
      get :edit_service   
    end
  end

  match '/index_service', to: 'fd_produtos#index_service', via: 'get'
  match '/new_service', to: 'fd_produtos#new_service', via: 'get'


  resources :fd_variacaos
  resources :fd_formapagamentos
  resources :fd_statuses
  resources :fd_variacaoprodutos
  resources :fd_itensprodutos
  resources :fd_itensadicionals
  resources :fd_items
  resources :fd_funcionarios
  resources :fd_cargos
  resources :fd_produtos
  resources :fd_categoriaprodutos
  resources :fd_mesas
  resources :fd_clientes

  root  'static_pages#home'
  match '/report', to: 'static_pages#report', via: 'get'
  match '/config2', to: 'static_pages#config2', via: 'get'
  match '/inclui_cliente', to: 'fd_clientes#inclui_cliente', via: 'get'
  match '/atualiza_cliente', to: 'fd_clientes#atualiza_cliente', via: 'get'
  match '/buscaCliente', to: 'fd_clientes#buscaCliente', via: 'get'
  match '/buscaClientetelefone', to: 'fd_clientes#buscaClientetelefone', via: 'get'

  resources :fd_usuarios
  resources :fd_empresas
  resources :fd_categoriaempresas
  resources :fd_enderecos
  resources :fd_cidades
  resources :fd_estados

  match '/listarCidade', to: 'fd_cidades#get_cities', via: 'get'
  
  match '/login', to: 'fd_autentication#login', via: 'get'
  match '/login', to: 'fd_autentication#login', via: 'post'
  match '/logoff', to: 'fd_autentication#logoff', via: 'get'

  match '/tipo_pedido', to: 'static_pedidos#tipo_pedido', via: 'get'
  match '/lista_mesas', to: 'static_pedidos#lista_mesas', via: 'get'
  get '/pedidos/:fd_mesa_id/:fd_pedido_id/:tipo_atendimento', to: 'static_pedidos#pedidos', as: 'pedidos'

  get '/lista_pedidos/:fd_mesa_id/:tipo_atendimento', to: 'static_pedidos#lista_pedidos', as: 'lista_pedidos'

  get '/fecha_pedido/:fd_mesa_id/:fd_pedido_id', to: 'static_pedidos#fecha_pedido', as: 'fecha_pedido'

  match '/buscaCategoriaProdutos', to: 'fd_categoriaprodutos#buscaCategoriaProdutos', via: 'get'
  match '/busca_produtos', to: 'fd_produtos#busca_produtos', via: 'get'
  match '/busca_variacaoprodutos', to: 'fd_variacaoprodutos#busca_variacaoprodutos', via: 'get'
  match '/insere_itempedido', to: 'fd_itempedidos#insere_itempedido', via: 'get'

  match '/salva_observacao', to: 'fd_itempedidos#salva_observacao', via: 'get'
  
  match '/atualiza_tipoatendimento', to: 'fd_itempedidos#atualiza_tipoatendimento', via: 'get'
  
  match '/busca_itempedido', to: 'fd_itempedidos#busca_itempedido', via: 'get'
  match '/busca_itemcomanda', to: 'fd_itempedidos#busca_itemcomanda', via: 'get'
  match '/busca_itemcomanda_adicionais', to: 'fd_itempedidos#busca_itemcomanda_adicionais', via: 'get'
  match '/exclui_itempedido', to: 'fd_itempedidos#exclui_itempedido', via: 'get'
  match '/exclui_servicopedido', to: 'fd_itempedidos#exclui_servicopedido', via: 'get'
  match '/insere_variacao_produto', to: 'fd_produtos#salva_variacao_produto', via: 'get'
  match '/busca_item', to: 'fd_itensprodutos#busca_item', via: 'get'
  match '/busca_itemMisto', to: 'fd_itensprodutos#busca_itemMisto', via: 'get'
  match '/insere_ingredientealterado', to: 'fd_itemalterados#insere_ingredientealterado', via: 'get'
  match '/insere_ingredientealteradoMisto', to: 'fd_itemalterados#insere_ingredientealteradoMisto', via: 'get'
  match '/exclui_variacao_produto', to: 'fd_produtos#exclui_variacao_produto', via: 'get'
  match '/busca_items', to: 'fd_produtos#busca_item', via: 'get'
  match '/busca_itemsproduto', to: 'fd_produtos#busca_item_produto', via: 'get'
  match '/busca_itemadicional', to: 'fd_itensadicionals#busca_itemadicional', via: 'get'
  match '/insere_adicionais', to: 'fd_adicionaisinclusos#insere_adicionais', via: 'get'
  match '/salva_item_produto', to: 'fd_produtos#salva_item_produto', via: 'get'
  match '/exclui_item_produto', to: 'fd_produtos#exclui_item_produto', via: 'get'
  match '/busca_trocas', to: 'fd_pedidocombos#busca_trocas', via: 'get'
  match '/busca_produto', to: 'fd_produtos#busca_produto', via: 'get'
  match '/busca_produto_trocas', to: 'fd_produtotrocacombos#busca_produto_trocas', via: 'get'
  match '/troca_produtos_combo', to: 'fd_pedidocombos#troca_produtos_combo', via: 'get'
  match '/inclui_produto_combo', to: 'fd_produtos#inclui_produto_combo', via: 'get'
  match '/busca_produto_combo', to: 'fd_produtos#busca_produto_combo', via: 'get'
  match '/exclui_produto_combo', to: 'fd_produtos#exclui_produto_combo', via: 'get'
  match '/inclui_produto_troca', to: 'fd_produtos#inclui_produto_troca', via: 'get'
  match '/exclui_produto_troca', to: 'fd_produtos#exclui_produto_troca', via: 'get'
  match '/inclui_item_adicinal', to: 'fd_itensadicionals#inclui_item_adicinal', via: 'get'
  match '/exclui_item_adicinal', to: 'fd_itensadicionals#exclui_item_adicinal', via: 'get'
  match '/relPedidos', to: 'fd_pedidos#relPedidos', via: 'get'
  match '/busca_Servicos', to: 'fd_produtos#busca_Servicos', via: 'get'
  match '/insere_pedidomisto', to: 'fd_itempedidos#insere_pedidomisto', via: 'get'
  match '/busca_DetalhesMistos', to: 'fd_pedidomistos#busca_DetalhesMistos', via: 'get'
  match '/lista_pedidos_geral', to: 'static_pedidos#lista_pedidos_geral', via: 'get'
  match '/busca_pedidos_geral', to: 'static_pedidos#busca_pedidos_geral', via: 'get'
  match '/muda_sitaucao_pedido', to: 'static_pedidos#muda_sitaucao_pedido', via: 'get'
  match '/efetua_pagamento', to: 'fd_pedidos#efetua_pagamento', via: 'get'
  match '/busca_caixa_aberto', to: 'fd_caixas#busca_caixa_aberto', via: 'get'
  match '/fechar_caixa', to: 'fd_caixas#fechar_caixa', via: 'get'
  match '/trocarempresa', to: 'fd_usuarios#troca_empresa', via: 'get'
  
  match '/relCaixas', to: 'fd_caixas#relCaixas', via: 'get'

  get '/relPedidosListagem/:fd_caixa_id/', to: 'static_pedidos#relPedidosListagem', as: 'relPedidosListagem'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :requer_logon

def config2
end

def home		
 
	 if params[:q] == "abrir"       
	 	
        @caixa = FdCaixa.where(fd_empresa_id: user.fd_empresa_id, data_fechamento: nil)

        if !@caixa.first
		 	@fd_caixa = FdCaixa.new
		    @fd_caixa.numr_contador = 0
		    @fd_caixa.data_abertura = Time.now
		    @fd_caixa.fd_empresa_id = user.fd_empresa_id
		    @fd_caixa.save
	    end
	 end

	@caixa = FdCaixa.where(fd_empresa_id: user.fd_empresa_id, data_fechamento: nil)
	    
	if @caixa.first
	   	@caixa_aberto = true
	   else
	   	@caixa_aberto = false
	end

	@fd_pedidos = FdPedido.joins(:fd_caixa).where(:fd_empresa_id => user.fd_empresa_id, :fd_situacao_id => 1, fd_caixas: { data_fechamento: nil}) rescue nil    	


 @fd_caixa = FdCaixa.new

end 

def report

end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/config2.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Configurações</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">
    <div class="row mar-bot40">
      <div class="col-lg-2" >
        <%= link_to fd_clientes_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-piggy-bank"></span> Clientes
        <% end %>
      </div>
      <div class="col-lg-2" >
        <%= link_to fd_caixas_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-usd"></span> Caixas
        <% end %>         
      </div>
      <div class="col-lg-2" >
        <%= link_to fd_usuarios_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-user"></span> Usuários
        <% end %>         
      </div>
      <div class="col-lg-2" >
        <%= link_to fd_mesas_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-cutlery"></span> Mesas
        <% end %>         
      </div>
      <div class="col-lg-3" >
        <%= link_to fd_categoriaprodutos_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-th-list"></span> Categorias Produtos
        <% end %>         
      </div> 
    </div> 
    <br/>
    <div class="row mar-bot40">
      <div class="col-lg-2" >
        <%= link_to fd_produtos_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-shopping-cart"></span> Produtos
        <% end %>         
      </div>
      <div class="col-lg-2" >
        <%= link_to index_service_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-cog"></span> Serviços
        <% end %>         
      </div>
      <div class="col-lg-2" >
        <%= link_to fd_items_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-tag"></span> Itens
        <% end %>         
      </div>
      <div class="col-lg-2" >
        <%= link_to fd_itensadicionals_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-plus"></span> Adicionais
        <% end %>         
      </div>      
      <div class="col-lg-2" >
        <%= link_to report_path, :class => "btn btn-default btn-lg", :rel=>"tooltip", :title=>"Exibir" do %>
          <span class="glyphicon glyphicon-list-alt"></span> Relatórios
        <% end %>         
      </div>            
    </br>
    </br>
  </div>
</div>

app/views/static_pages/home.html.erb
<% flash.each do |name, msg| -%>
  <div class="alert alert-warning alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%=msg%>
  </div>      
<% end %>



<div class="alert alert-danger" role="alert"><b>Mensagem Automatica:</b> Atenção, o pagamento da mensalidade com vencimento <b>05/08/2015</b> não foi encontrado em nosso sistema. Caso já tenha regularizado a situação, aguarde 24 horas para a compensação do pagamento. Obrigado.</div>

<%#= render 'static_pedidos/tipo_pedido' %>

app/views/static_pages/report.html.erb
   <p><%= link_to "Relatório de Vendas",  relPedidos_path %></p>
   <p><%= link_to "Relatório de Caixas",  relCaixas_path %></p>