config/routes.rb
Food::Application.routes.draw do

  resources :fd_caixas do
    member do
      get :troca_caixa
    end
  end

  resources :fd_entregas
  match '/insere_entrega', to: 'fd_entregas#insere_entrega', via: 'get'
  

  resources :fd_pedidomistos

  resources :fd_situacoes

  resources :fd_produtotrocacombos

  resources :fd_pedidocombos

  resources :fd_produtocombos

  resources :fd_adicionaisinclusos

  resources :fd_itemalterados
  resources :fd_itempedidos
  resources :fd_pedidos
  resources :fd_categoriaprodutos

  resources :fd_produtos do
    member do
      get :show_service   
      get :edit_service   
    end
  end

  match '/index_service', to: 'fd_produtos#index_service', via: 'get'
  match '/new_service', to: 'fd_produtos#new_service', via: 'get'


  resources :fd_variacaos
  resources :fd_formapagamentos
  resources :fd_statuses
  resources :fd_variacaoprodutos
  resources :fd_itensprodutos
  resources :fd_itensadicionals
  resources :fd_items
  resources :fd_funcionarios
  resources :fd_cargos
  resources :fd_produtos
  resources :fd_categoriaprodutos
  resources :fd_mesas
  resources :fd_clientes

  root  'static_pages#home'
  match '/report', to: 'static_pages#report', via: 'get'
  match '/config2', to: 'static_pages#config2', via: 'get'
  match '/inclui_cliente', to: 'fd_clientes#inclui_cliente', via: 'get'
  match '/atualiza_cliente', to: 'fd_clientes#atualiza_cliente', via: 'get'
  match '/buscaCliente', to: 'fd_clientes#buscaCliente', via: 'get'
  match '/buscaClientetelefone', to: 'fd_clientes#buscaClientetelefone', via: 'get'

  resources :fd_usuarios
  resources :fd_empresas
  resources :fd_categoriaempresas
  resources :fd_enderecos
  resources :fd_cidades
  resources :fd_estados

  match '/listarCidade', to: 'fd_cidades#get_cities', via: 'get'
  
  match '/login', to: 'fd_autentication#login', via: 'get'
  match '/login', to: 'fd_autentication#login', via: 'post'
  match '/logoff', to: 'fd_autentication#logoff', via: 'get'

  match '/tipo_pedido', to: 'static_pedidos#tipo_pedido', via: 'get'
  match '/lista_mesas', to: 'static_pedidos#lista_mesas', via: 'get'
  get '/pedidos/:fd_mesa_id/:fd_pedido_id/:tipo_atendimento', to: 'static_pedidos#pedidos', as: 'pedidos'

  get '/lista_pedidos/:fd_mesa_id/:tipo_atendimento', to: 'static_pedidos#lista_pedidos', as: 'lista_pedidos'

  get '/fecha_pedido/:fd_mesa_id/:fd_pedido_id', to: 'static_pedidos#fecha_pedido', as: 'fecha_pedido'

  match '/buscaCategoriaProdutos', to: 'fd_categoriaprodutos#buscaCategoriaProdutos', via: 'get'
  match '/busca_produtos', to: 'fd_produtos#busca_produtos', via: 'get'
  match '/busca_variacaoprodutos', to: 'fd_variacaoprodutos#busca_variacaoprodutos', via: 'get'
  match '/insere_itempedido', to: 'fd_itempedidos#insere_itempedido', via: 'get'

  match '/salva_observacao', to: 'fd_itempedidos#salva_observacao', via: 'get'
  
  match '/atualiza_tipoatendimento', to: 'fd_itempedidos#atualiza_tipoatendimento', via: 'get'
  
  match '/busca_itempedido', to: 'fd_itempedidos#busca_itempedido', via: 'get'
  match '/busca_itemcomanda', to: 'fd_itempedidos#busca_itemcomanda', via: 'get'
  match '/busca_itemcomanda_adicionais', to: 'fd_itempedidos#busca_itemcomanda_adicionais', via: 'get'
  match '/exclui_itempedido', to: 'fd_itempedidos#exclui_itempedido', via: 'get'
  match '/exclui_servicopedido', to: 'fd_itempedidos#exclui_servicopedido', via: 'get'
  match '/insere_variacao_produto', to: 'fd_produtos#salva_variacao_produto', via: 'get'
  match '/busca_item', to: 'fd_itensprodutos#busca_item', via: 'get'
  match '/busca_itemMisto', to: 'fd_itensprodutos#busca_itemMisto', via: 'get'
  match '/insere_ingredientealterado', to: 'fd_itemalterados#insere_ingredientealterado', via: 'get'
  match '/insere_ingredientealteradoMisto', to: 'fd_itemalterados#insere_ingredientealteradoMisto', via: 'get'
  match '/exclui_variacao_produto', to: 'fd_produtos#exclui_variacao_produto', via: 'get'
  match '/busca_items', to: 'fd_produtos#busca_item', via: 'get'
  match '/busca_itemsproduto', to: 'fd_produtos#busca_item_produto', via: 'get'
  match '/busca_itemadicional', to: 'fd_itensadicionals#busca_itemadicional', via: 'get'
  match '/insere_adicionais', to: 'fd_adicionaisinclusos#insere_adicionais', via: 'get'
  match '/salva_item_produto', to: 'fd_produtos#salva_item_produto', via: 'get'
  match '/exclui_item_produto', to: 'fd_produtos#exclui_item_produto', via: 'get'
  match '/busca_trocas', to: 'fd_pedidocombos#busca_trocas', via: 'get'
  match '/busca_produto', to: 'fd_produtos#busca_produto', via: 'get'
  match '/busca_produto_trocas', to: 'fd_produtotrocacombos#busca_produto_trocas', via: 'get'
  match '/troca_produtos_combo', to: 'fd_pedidocombos#troca_produtos_combo', via: 'get'
  match '/inclui_produto_combo', to: 'fd_produtos#inclui_produto_combo', via: 'get'
  match '/busca_produto_combo', to: 'fd_produtos#busca_produto_combo', via: 'get'
  match '/exclui_produto_combo', to: 'fd_produtos#exclui_produto_combo', via: 'get'
  match '/inclui_produto_troca', to: 'fd_produtos#inclui_produto_troca', via: 'get'
  match '/exclui_produto_troca', to: 'fd_produtos#exclui_produto_troca', via: 'get'
  match '/inclui_item_adicinal', to: 'fd_itensadicionals#inclui_item_adicinal', via: 'get'
  match '/exclui_item_adicinal', to: 'fd_itensadicionals#exclui_item_adicinal', via: 'get'
  match '/relPedidos', to: 'fd_pedidos#relPedidos', via: 'get'
  match '/busca_Servicos', to: 'fd_produtos#busca_Servicos', via: 'get'
  match '/insere_pedidomisto', to: 'fd_itempedidos#insere_pedidomisto', via: 'get'
  match '/busca_DetalhesMistos', to: 'fd_pedidomistos#busca_DetalhesMistos', via: 'get'
  match '/lista_pedidos_geral', to: 'static_pedidos#lista_pedidos_geral', via: 'get'
  match '/busca_pedidos_geral', to: 'static_pedidos#busca_pedidos_geral', via: 'get'
  match '/muda_sitaucao_pedido', to: 'static_pedidos#muda_sitaucao_pedido', via: 'get'
  match '/efetua_pagamento', to: 'fd_pedidos#efetua_pagamento', via: 'get'
  match '/busca_caixa_aberto', to: 'fd_caixas#busca_caixa_aberto', via: 'get'
  match '/fechar_caixa', to: 'fd_caixas#fechar_caixa', via: 'get'
  match '/trocarempresa', to: 'fd_usuarios#troca_empresa', via: 'get'
  
  match '/relCaixas', to: 'fd_caixas#relCaixas', via: 'get'

  get '/relPedidosListagem/:fd_caixa_id/', to: 'static_pedidos#relPedidosListagem', as: 'relPedidosListagem'

end

app/models/fd_pedido.rb
class FdPedido < ActiveRecord::Base
  belongs_to :fd_empresa
  belongs_to :fd_cliente
  belongs_to :fd_mesa
  belongs_to :fd_funcionario
  belongs_to :fd_formapagamento
  belongs_to :fd_situacao#, :class_name => "FdSituacao", :foreign_key => 'fd_situacao_id'
  belongs_to :fd_caixa
end

app/controllers/fd_pedidos_controller.rb
class FdPedidosController < ApplicationController
  before_action :set_fd_pedido, only: [:show, :edit, :update, :destroy]


  def efetua_pagamento

    params[:valr_pedido] = params[:valr_pedido].gsub('R$', '')
    params[:valr_pedido] = params[:valr_pedido].gsub('.', '')
    params[:valr_pedido] = params[:valr_pedido].gsub(',', '.').to_f    

    fd_pedido = FdPedido.find(params[:fd_pedido_id])
    fd_pedido.valr_pedido = params[:valr_pedido]
    fd_pedido.flag_pago = true
    fd_pedido.save

    render :json => {}

  end


  def relPedidos
    
  if params[:dataInicio] && params[:dataInicio] != ""
      dateInicio =  params[:dataInicio]     
      dateInicio = dateInicio.to_datetime.strftime('%a %b %d %H:%M:%S %Z %Y')
    
    else
     dateInicio = Time.new - 43200
  end
  if params[:dataFim] && params[:dataFim] != ""
     dateFim = params[:dataFim] 
     dateFim = dateFim.to_datetime.strftime('%a %b %d %H:%M:%S %Z %Y')
   else
    dateFim = Time.new
  end
   
   #debugger

    @fd_itempedidos = FdItempedido.where(created_at: (dateInicio)..dateFim, fd_empresa_id: user.fd_empresa_id)
    @valor_total =  @fd_itempedidos.sum("valr_item")

  end


  # GET /fd_pedidos
  def index
    @fd_pedidos = FdPedido.all
  end

  # GET /fd_pedidos/1
  def show
  end

  # GET /fd_pedidos/new
  def new
    @fd_pedido = FdPedido.new
  end

  # GET /fd_pedidos/1/edit
  def edit
  end

  # POST /fd_pedidos
  def create
    @fd_pedido = FdPedido.new(fd_pedido_params)

    if @fd_pedido.save
      redirect_to @fd_pedido, notice: 'Fd pedido was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /fd_pedidos/1
  def update
    if @fd_pedido.update(fd_pedido_params)
      redirect_to @fd_pedido, notice: 'Fd pedido was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /fd_pedidos/1
  def destroy
    @fd_pedido.destroy
    redirect_to fd_pedidos_url, notice: 'Fd pedido was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fd_pedido
      @fd_pedido = FdPedido.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def fd_pedido_params
      params.require(:fd_pedido).permit(:tipo_atendimento, :valr_pedido, :flag_pago, :fd_empresa_id, :fd_cliente_id, :fd_mesa_id, :fd_funcionario_id, :fd_formapagamento_id, :fd_status_id)
    end
end

app/helpers/fd_pedidos_helper.rb
module FdPedidosHelper
end

app/views/fd_pedidos/_form.html.erb
<%= form_for(@fd_pedido) do |f| %>
  <% if @fd_pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fd_pedido.errors.count, "error") %> prohibited this fd_pedido from being saved:</h2>

      <ul>
      <% @fd_pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valr_pedido %><br>
    <%= f.text_field :valr_pedido %>
  </div>
  <div class="field">
    <%= f.label :flag_pago %><br>
    <%= f.check_box :flag_pago %>
  </div>
  <div class="field">
    <%= f.label :fd_empresa_id %><br>
    <%= f.text_field :fd_empresa_id %>
  </div>
  <div class="field">
    <%= f.label :fd_cliente_id %><br>
    <%= f.text_field :fd_cliente_id %>
  </div>
  <div class="field">
    <%= f.label :fd_mesa_id %><br>
    <%= f.text_field :fd_mesa_id %>
  </div>
  <div class="field">
    <%= f.label :fd_funcionario_id %><br>
    <%= f.text_field :fd_funcionario_id %>
  </div>
  <div class="field">
    <%= f.label :fd_formapagamento_id %><br>
    <%= f.text_field :fd_formapagamento_id %>
  </div>
  <div class="field">
    <%= f.label :fd_status_id %><br>
    <%= f.text_field :fd_status_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fd_pedidos/edit.html.erb
<h1>Editing fd_pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @fd_pedido %> |
<%= link_to 'Back', fd_pedidos_path %>

app/views/fd_pedidos/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Listar Pedidos</h3></div>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Valor</th>
          <th>Mesa</th>
          <th>Pagamento</th>
          <th>Situação</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @fd_pedidos.each do |fd_pedido| %>
          <tr>
            <td><%= fd_pedido.valr_pedido %></td>
            <td><%= fd_pedido.fd_mesa.numr_mesa %></td>
            <td><%= fd_pedido.fd_formapagamento %></td>
            <td><%= fd_pedido.fd_situacao.nome_situacao %></td>
            <td align="right">
              <div class="btn-group">
                <%= link_to fd_pedido, :class => "btn btn-default btn-sm" do %>
                  <span class="glyphicon glyphicon-list-alt"></span> Exibir
                <% end %>             
                <%= link_to edit_fd_pedido_path(fd_pedido), :class => "btn btn-default btn-sm" do %>
                  <span class="glyphicon glyphicon-pencil"></span> Editar
                <% end %>             
                <%= link_to fd_pedido , :method => :delete,  :confirm => 'Deseja excluir o registro?', :class => "btn btn-default btn-sm" do %>
                  <span class="glyphicon glyphicon-trash"></span> Excluir
                <% end %>            
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>

  <%= link_to new_fd_pedido_path, :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-file"></span>Novo
  <% end %>

app/views/fd_pedidos/new.html.erb
<h1>New fd_pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', fd_pedidos_path %>

app/views/fd_pedidos/relPedidos.html.erb
<%

if params[:fechado]
  fechado = true
end

if params[:aberto]
  aberto = true
end

%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cadastro Itens Adicionais</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

 <%= form_tag nil, method: 'GET' do %>
  <div lass="row mar-bot40">
    <div class="col-lg-2">
    	 <label >Data Início</label><br>
        <input id="dataInicio" name="dataInicio" type="text" class="form-control">
    </div><!-- /.col-lg-6 -->
    <div class="col-lg-2">
    	 <label >Data Fim</label><br>
        <input id="dataFim" name="dataFim" type="text" class="form-control">
    </div><!-- /.col-lg-6 -->
   
    <div class="col-lg-2" >
    	<label >Pedidos</label><br>
          <div class="checkbox">
            <label>
              <input type="checkbox" id="discipulador" name="discipulador" value="true" <%=fechado ? 'checked="checked"' : ''%> > Fechado
            </label>
            <label>
              <input type="checkbox" id="consolidador" name="consolidador" value="true" <%=aberto ? 'checked="checked"' : ''%> > Aberto
            </label>          
          </div>              
     </div>

	 <div class="col-lg-1" style="margin-top:17px;"  >
	   <button class="btn btn-success" type="submit" >Gerar</button>
	 </div>

  <div class="col-lg-2">
  </div>

 <div class="col-lg-3" style="margin-top:0px;" >
  <div class="input-group input-group-lg">
    <span class="input-group-addon" id="sizing-addon1">Total</span>
    <input type="text" class="form-control" value="<%=number_to_currency(@valor_total, unit: "R$", separator: ",", delimiter: "")%>" disabled="disabled" aria-describedby="sizing-addon1">
  </div>
</div>

 </div><!-- /.row -->
  
<% end %>

    <table class="table table-hover" >
      <thead>
        <tr>
          <th>Produto</th>
          <th>Data</th>
          <th>Valor</th>
        </tr>
      </thead>

      <tbody>
        <% @fd_itempedidos.each do |fd_itempedido| %>
          <tr>
            <td><%= fd_itempedido.fd_variacaoproduto.fd_produto.nome_produto %></td>
            <td><%= fd_itempedido.created_at.blank? ? '' : fd_itempedido.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= number_to_currency(fd_itempedido.valr_item, unit: "R$", separator: ",", delimiter: "") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
 
 <script>


jQuery(function($){
  $("#dataInicio").mask("99/99/9999 99:99");
  $("#dataFim").mask("99/99/9999 99:99");
 });

 </script>

app/views/fd_pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valr pedido:</strong>
  <%= @fd_pedido.valr_pedido %>
</p>

<p>
  <strong>Flag pago:</strong>
  <%= @fd_pedido.flag_pago %>
</p>

<p>
  <strong>Fd empresa:</strong>
  <%= @fd_pedido.fd_empresa %>
</p>

<p>
  <strong>Fd cliente:</strong>
  <%= @fd_pedido.fd_cliente %>
</p>

<p>
  <strong>Fd mesa:</strong>
  <%= @fd_pedido.fd_mesa %>
</p>

<p>
  <strong>Fd funcionario:</strong>
  <%= @fd_pedido.fd_funcionario %>
</p>

<p>
  <strong>Fd formapagamento:</strong>
  <%= @fd_pedido.fd_formapagamento %>
</p>

<p>
  <strong>Fd status:</strong>
  <%= @fd_pedido.fd_status %>
</p>

<%= link_to 'Edit', edit_fd_pedido_path(@fd_pedido) %> |
<%= link_to 'Back', fd_pedidos_path %>