config/routes.rb
Food::Application.routes.draw do

  resources :fd_caixas do
    member do
      get :troca_caixa
    end
  end

  resources :fd_entregas
  match '/insere_entrega', to: 'fd_entregas#insere_entrega', via: 'get'
  

  resources :fd_pedidomistos

  resources :fd_situacoes

  resources :fd_produtotrocacombos

  resources :fd_pedidocombos

  resources :fd_produtocombos

  resources :fd_adicionaisinclusos

  resources :fd_itemalterados
  resources :fd_itempedidos
  resources :fd_pedidos
  resources :fd_categoriaprodutos

  resources :fd_produtos do
    member do
      get :show_service   
      get :edit_service   
    end
  end

  match '/index_service', to: 'fd_produtos#index_service', via: 'get'
  match '/new_service', to: 'fd_produtos#new_service', via: 'get'


  resources :fd_variacaos
  resources :fd_formapagamentos
  resources :fd_statuses
  resources :fd_variacaoprodutos
  resources :fd_itensprodutos
  resources :fd_itensadicionals
  resources :fd_items
  resources :fd_funcionarios
  resources :fd_cargos
  resources :fd_produtos
  resources :fd_categoriaprodutos
  resources :fd_mesas
  resources :fd_clientes

  root  'static_pages#home'
  match '/report', to: 'static_pages#report', via: 'get'
  match '/config2', to: 'static_pages#config2', via: 'get'
  match '/inclui_cliente', to: 'fd_clientes#inclui_cliente', via: 'get'
  match '/atualiza_cliente', to: 'fd_clientes#atualiza_cliente', via: 'get'
  match '/buscaCliente', to: 'fd_clientes#buscaCliente', via: 'get'
  match '/buscaClientetelefone', to: 'fd_clientes#buscaClientetelefone', via: 'get'

  resources :fd_usuarios
  resources :fd_empresas
  resources :fd_categoriaempresas
  resources :fd_enderecos
  resources :fd_cidades
  resources :fd_estados

  match '/listarCidade', to: 'fd_cidades#get_cities', via: 'get'
  
  match '/login', to: 'fd_autentication#login', via: 'get'
  match '/login', to: 'fd_autentication#login', via: 'post'
  match '/logoff', to: 'fd_autentication#logoff', via: 'get'

  match '/tipo_pedido', to: 'static_pedidos#tipo_pedido', via: 'get'
  match '/lista_mesas', to: 'static_pedidos#lista_mesas', via: 'get'
  get '/pedidos/:fd_mesa_id/:fd_pedido_id/:tipo_atendimento', to: 'static_pedidos#pedidos', as: 'pedidos'

  get '/lista_pedidos/:fd_mesa_id/:tipo_atendimento', to: 'static_pedidos#lista_pedidos', as: 'lista_pedidos'

  get '/fecha_pedido/:fd_mesa_id/:fd_pedido_id', to: 'static_pedidos#fecha_pedido', as: 'fecha_pedido'

  match '/buscaCategoriaProdutos', to: 'fd_categoriaprodutos#buscaCategoriaProdutos', via: 'get'
  match '/busca_produtos', to: 'fd_produtos#busca_produtos', via: 'get'
  match '/busca_variacaoprodutos', to: 'fd_variacaoprodutos#busca_variacaoprodutos', via: 'get'
  match '/insere_itempedido', to: 'fd_itempedidos#insere_itempedido', via: 'get'

  match '/salva_observacao', to: 'fd_itempedidos#salva_observacao', via: 'get'
  
  match '/atualiza_tipoatendimento', to: 'fd_itempedidos#atualiza_tipoatendimento', via: 'get'
  
  match '/busca_itempedido', to: 'fd_itempedidos#busca_itempedido', via: 'get'
  match '/busca_itemcomanda', to: 'fd_itempedidos#busca_itemcomanda', via: 'get'
  match '/busca_itemcomanda_adicionais', to: 'fd_itempedidos#busca_itemcomanda_adicionais', via: 'get'
  match '/exclui_itempedido', to: 'fd_itempedidos#exclui_itempedido', via: 'get'
  match '/exclui_servicopedido', to: 'fd_itempedidos#exclui_servicopedido', via: 'get'
  match '/insere_variacao_produto', to: 'fd_produtos#salva_variacao_produto', via: 'get'
  match '/busca_item', to: 'fd_itensprodutos#busca_item', via: 'get'
  match '/busca_itemMisto', to: 'fd_itensprodutos#busca_itemMisto', via: 'get'
  match '/insere_ingredientealterado', to: 'fd_itemalterados#insere_ingredientealterado', via: 'get'
  match '/insere_ingredientealteradoMisto', to: 'fd_itemalterados#insere_ingredientealteradoMisto', via: 'get'
  match '/exclui_variacao_produto', to: 'fd_produtos#exclui_variacao_produto', via: 'get'
  match '/busca_items', to: 'fd_produtos#busca_item', via: 'get'
  match '/busca_itemsproduto', to: 'fd_produtos#busca_item_produto', via: 'get'
  match '/busca_itemadicional', to: 'fd_itensadicionals#busca_itemadicional', via: 'get'
  match '/insere_adicionais', to: 'fd_adicionaisinclusos#insere_adicionais', via: 'get'
  match '/salva_item_produto', to: 'fd_produtos#salva_item_produto', via: 'get'
  match '/exclui_item_produto', to: 'fd_produtos#exclui_item_produto', via: 'get'
  match '/busca_trocas', to: 'fd_pedidocombos#busca_trocas', via: 'get'
  match '/busca_produto', to: 'fd_produtos#busca_produto', via: 'get'
  match '/busca_produto_trocas', to: 'fd_produtotrocacombos#busca_produto_trocas', via: 'get'
  match '/troca_produtos_combo', to: 'fd_pedidocombos#troca_produtos_combo', via: 'get'
  match '/inclui_produto_combo', to: 'fd_produtos#inclui_produto_combo', via: 'get'
  match '/busca_produto_combo', to: 'fd_produtos#busca_produto_combo', via: 'get'
  match '/exclui_produto_combo', to: 'fd_produtos#exclui_produto_combo', via: 'get'
  match '/inclui_produto_troca', to: 'fd_produtos#inclui_produto_troca', via: 'get'
  match '/exclui_produto_troca', to: 'fd_produtos#exclui_produto_troca', via: 'get'
  match '/inclui_item_adicinal', to: 'fd_itensadicionals#inclui_item_adicinal', via: 'get'
  match '/exclui_item_adicinal', to: 'fd_itensadicionals#exclui_item_adicinal', via: 'get'
  match '/relPedidos', to: 'fd_pedidos#relPedidos', via: 'get'
  match '/busca_Servicos', to: 'fd_produtos#busca_Servicos', via: 'get'
  match '/insere_pedidomisto', to: 'fd_itempedidos#insere_pedidomisto', via: 'get'
  match '/busca_DetalhesMistos', to: 'fd_pedidomistos#busca_DetalhesMistos', via: 'get'
  match '/lista_pedidos_geral', to: 'static_pedidos#lista_pedidos_geral', via: 'get'
  match '/busca_pedidos_geral', to: 'static_pedidos#busca_pedidos_geral', via: 'get'
  match '/muda_sitaucao_pedido', to: 'static_pedidos#muda_sitaucao_pedido', via: 'get'
  match '/efetua_pagamento', to: 'fd_pedidos#efetua_pagamento', via: 'get'
  match '/busca_caixa_aberto', to: 'fd_caixas#busca_caixa_aberto', via: 'get'
  match '/fechar_caixa', to: 'fd_caixas#fechar_caixa', via: 'get'
  match '/trocarempresa', to: 'fd_usuarios#troca_empresa', via: 'get'
  
  match '/relCaixas', to: 'fd_caixas#relCaixas', via: 'get'

  get '/relPedidosListagem/:fd_caixa_id/', to: 'static_pedidos#relPedidosListagem', as: 'relPedidosListagem'

end

app/models/fd_funcionario.rb
class FdFuncionario < ActiveRecord::Base
  belongs_to :fd_cargo
  belongs_to :fd_endereco
  belongs_to :fd_empresa
  belongs_to :inclusao, :class_name => "FdUsuario", :foreign_key => "user_inclusao"
  belongs_to :exclusao, :class_name => "FdUsuario", :foreign_key => "user_exclusao"
end

app/controllers/fd_funcionarios_controller.rb
class FdFuncionariosController < ApplicationController
  before_action :set_fd_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /fd_funcionarios
  def index
    @fd_funcionarios = FdFuncionario.all
  end

  # GET /fd_funcionarios/1
  def show
  end

  # GET /fd_funcionarios/new
  def new
    @fd_funcionario = FdFuncionario.new
  end

  # GET /fd_funcionarios/1/edit
  def edit
  end

  # POST /fd_funcionarios
  def create
    @fd_funcionario = FdFuncionario.new(fd_funcionario_params)

    if @fd_funcionario.save
      redirect_to @fd_funcionario, notice: 'Fd funcionario was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /fd_funcionarios/1
  def update
    if @fd_funcionario.update(fd_funcionario_params)
      redirect_to @fd_funcionario, notice: 'Fd funcionario was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /fd_funcionarios/1
  def destroy
    @fd_funcionario.destroy
    redirect_to fd_funcionarios_url, notice: 'Fd funcionario was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fd_funcionario
      @fd_funcionario = FdFuncionario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def fd_funcionario_params
      params.require(:fd_funcionario).permit(:nome_funcionario, :desc_telefone, :desc_celular, :data_exclusao, :fd_cargo_id, :fd_endereco_id, :fd_empresa_id)
    end
end

app/helpers/fd_funcionarios_helper.rb
module FdFuncionariosHelper
end

app/views/fd_funcionarios/_form.html.erb
<%= form_for(@fd_funcionario) do |f| %>
  <% if @fd_funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fd_funcionario.errors.count, "error") %> prohibited this fd_funcionario from being saved:</h2>

      <ul>
      <% @fd_funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_funcionario %><br>
    <%= f.text_field :nome_funcionario %>
  </div>
  <div class="field">
    <%= f.label :desc_telefone %><br>
    <%= f.text_field :desc_telefone %>
  </div>
  <div class="field">
    <%= f.label :desc_celular %><br>
    <%= f.text_field :desc_celular %>
  </div>
  <div class="field">
    <%= f.label :data_exclusao %><br>
    <%= f.datetime_select :data_exclusao %>
  </div>
  <div class="field">
    <%= f.label :fd_cargo_id %><br>
    <%= f.text_field :fd_cargo_id %>
  </div>
  <div class="field">
    <%= f.label :fd_endereco_id %><br>
    <%= f.text_field :fd_endereco_id %>
  </div>
  <div class="field">
    <%= f.label :fd_empresa_id %><br>
    <%= f.text_field :fd_empresa_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fd_funcionarios/edit.html.erb
<h1>Editing fd_funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @fd_funcionario %> |
<%= link_to 'Back', fd_funcionarios_path %>

app/views/fd_funcionarios/index.html.erb
<h1>Listing fd_funcionarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome funcionario</th>
      <th>Desc telefone</th>
      <th>Desc celular</th>
      <th>Data exclusao</th>
      <th>Fd cargo</th>
      <th>Fd endereco</th>
      <th>Fd empresa</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fd_funcionarios.each do |fd_funcionario| %>
      <tr>
        <td><%= fd_funcionario.nome_funcionario %></td>
        <td><%= fd_funcionario.desc_telefone %></td>
        <td><%= fd_funcionario.desc_celular %></td>
        <td><%= fd_funcionario.data_exclusao %></td>
        <td><%= fd_funcionario.fd_cargo %></td>
        <td><%= fd_funcionario.fd_endereco %></td>
        <td><%= fd_funcionario.fd_empresa %></td>
        <td><%= link_to 'Show', fd_funcionario %></td>
        <td><%= link_to 'Edit', edit_fd_funcionario_path(fd_funcionario) %></td>
        <td><%= link_to 'Destroy', fd_funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fd funcionario', new_fd_funcionario_path %>

app/views/fd_funcionarios/new.html.erb
<h1>New fd_funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', fd_funcionarios_path %>

app/views/fd_funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome funcionario:</strong>
  <%= @fd_funcionario.nome_funcionario %>
</p>

<p>
  <strong>Desc telefone:</strong>
  <%= @fd_funcionario.desc_telefone %>
</p>

<p>
  <strong>Desc celular:</strong>
  <%= @fd_funcionario.desc_celular %>
</p>

<p>
  <strong>Data exclusao:</strong>
  <%= @fd_funcionario.data_exclusao %>
</p>

<p>
  <strong>Fd cargo:</strong>
  <%= @fd_funcionario.fd_cargo %>
</p>

<p>
  <strong>Fd endereco:</strong>
  <%= @fd_funcionario.fd_endereco %>
</p>

<p>
  <strong>Fd empresa:</strong>
  <%= @fd_funcionario.fd_empresa %>
</p>

<%= link_to 'Edit', edit_fd_funcionario_path(@fd_funcionario) %> |
<%= link_to 'Back', fd_funcionarios_path %>