config/routes.rb
Food::Application.routes.draw do

  resources :fd_caixas do
    member do
      get :troca_caixa
    end
  end

  resources :fd_entregas
  match '/insere_entrega', to: 'fd_entregas#insere_entrega', via: 'get'
  

  resources :fd_pedidomistos

  resources :fd_situacoes

  resources :fd_produtotrocacombos

  resources :fd_pedidocombos

  resources :fd_produtocombos

  resources :fd_adicionaisinclusos

  resources :fd_itemalterados
  resources :fd_itempedidos
  resources :fd_pedidos
  resources :fd_categoriaprodutos

  resources :fd_produtos do
    member do
      get :show_service   
      get :edit_service   
    end
  end

  match '/index_service', to: 'fd_produtos#index_service', via: 'get'
  match '/new_service', to: 'fd_produtos#new_service', via: 'get'


  resources :fd_variacaos
  resources :fd_formapagamentos
  resources :fd_statuses
  resources :fd_variacaoprodutos
  resources :fd_itensprodutos
  resources :fd_itensadicionals
  resources :fd_items
  resources :fd_funcionarios
  resources :fd_cargos
  resources :fd_produtos
  resources :fd_categoriaprodutos
  resources :fd_mesas
  resources :fd_clientes

  root  'static_pages#home'
  match '/report', to: 'static_pages#report', via: 'get'
  match '/config2', to: 'static_pages#config2', via: 'get'
  match '/inclui_cliente', to: 'fd_clientes#inclui_cliente', via: 'get'
  match '/atualiza_cliente', to: 'fd_clientes#atualiza_cliente', via: 'get'
  match '/buscaCliente', to: 'fd_clientes#buscaCliente', via: 'get'
  match '/buscaClientetelefone', to: 'fd_clientes#buscaClientetelefone', via: 'get'

  resources :fd_usuarios
  resources :fd_empresas
  resources :fd_categoriaempresas
  resources :fd_enderecos
  resources :fd_cidades
  resources :fd_estados

  match '/listarCidade', to: 'fd_cidades#get_cities', via: 'get'
  
  match '/login', to: 'fd_autentication#login', via: 'get'
  match '/login', to: 'fd_autentication#login', via: 'post'
  match '/logoff', to: 'fd_autentication#logoff', via: 'get'

  match '/tipo_pedido', to: 'static_pedidos#tipo_pedido', via: 'get'
  match '/lista_mesas', to: 'static_pedidos#lista_mesas', via: 'get'
  get '/pedidos/:fd_mesa_id/:fd_pedido_id/:tipo_atendimento', to: 'static_pedidos#pedidos', as: 'pedidos'

  get '/lista_pedidos/:fd_mesa_id/:tipo_atendimento', to: 'static_pedidos#lista_pedidos', as: 'lista_pedidos'

  get '/fecha_pedido/:fd_mesa_id/:fd_pedido_id', to: 'static_pedidos#fecha_pedido', as: 'fecha_pedido'

  match '/buscaCategoriaProdutos', to: 'fd_categoriaprodutos#buscaCategoriaProdutos', via: 'get'
  match '/busca_produtos', to: 'fd_produtos#busca_produtos', via: 'get'
  match '/busca_variacaoprodutos', to: 'fd_variacaoprodutos#busca_variacaoprodutos', via: 'get'
  match '/insere_itempedido', to: 'fd_itempedidos#insere_itempedido', via: 'get'

  match '/salva_observacao', to: 'fd_itempedidos#salva_observacao', via: 'get'
  
  match '/atualiza_tipoatendimento', to: 'fd_itempedidos#atualiza_tipoatendimento', via: 'get'
  
  match '/busca_itempedido', to: 'fd_itempedidos#busca_itempedido', via: 'get'
  match '/busca_itemcomanda', to: 'fd_itempedidos#busca_itemcomanda', via: 'get'
  match '/busca_itemcomanda_adicionais', to: 'fd_itempedidos#busca_itemcomanda_adicionais', via: 'get'
  match '/exclui_itempedido', to: 'fd_itempedidos#exclui_itempedido', via: 'get'
  match '/exclui_servicopedido', to: 'fd_itempedidos#exclui_servicopedido', via: 'get'
  match '/insere_variacao_produto', to: 'fd_produtos#salva_variacao_produto', via: 'get'
  match '/busca_item', to: 'fd_itensprodutos#busca_item', via: 'get'
  match '/busca_itemMisto', to: 'fd_itensprodutos#busca_itemMisto', via: 'get'
  match '/insere_ingredientealterado', to: 'fd_itemalterados#insere_ingredientealterado', via: 'get'
  match '/insere_ingredientealteradoMisto', to: 'fd_itemalterados#insere_ingredientealteradoMisto', via: 'get'
  match '/exclui_variacao_produto', to: 'fd_produtos#exclui_variacao_produto', via: 'get'
  match '/busca_items', to: 'fd_produtos#busca_item', via: 'get'
  match '/busca_itemsproduto', to: 'fd_produtos#busca_item_produto', via: 'get'
  match '/busca_itemadicional', to: 'fd_itensadicionals#busca_itemadicional', via: 'get'
  match '/insere_adicionais', to: 'fd_adicionaisinclusos#insere_adicionais', via: 'get'
  match '/salva_item_produto', to: 'fd_produtos#salva_item_produto', via: 'get'
  match '/exclui_item_produto', to: 'fd_produtos#exclui_item_produto', via: 'get'
  match '/busca_trocas', to: 'fd_pedidocombos#busca_trocas', via: 'get'
  match '/busca_produto', to: 'fd_produtos#busca_produto', via: 'get'
  match '/busca_produto_trocas', to: 'fd_produtotrocacombos#busca_produto_trocas', via: 'get'
  match '/troca_produtos_combo', to: 'fd_pedidocombos#troca_produtos_combo', via: 'get'
  match '/inclui_produto_combo', to: 'fd_produtos#inclui_produto_combo', via: 'get'
  match '/busca_produto_combo', to: 'fd_produtos#busca_produto_combo', via: 'get'
  match '/exclui_produto_combo', to: 'fd_produtos#exclui_produto_combo', via: 'get'
  match '/inclui_produto_troca', to: 'fd_produtos#inclui_produto_troca', via: 'get'
  match '/exclui_produto_troca', to: 'fd_produtos#exclui_produto_troca', via: 'get'
  match '/inclui_item_adicinal', to: 'fd_itensadicionals#inclui_item_adicinal', via: 'get'
  match '/exclui_item_adicinal', to: 'fd_itensadicionals#exclui_item_adicinal', via: 'get'
  match '/relPedidos', to: 'fd_pedidos#relPedidos', via: 'get'
  match '/busca_Servicos', to: 'fd_produtos#busca_Servicos', via: 'get'
  match '/insere_pedidomisto', to: 'fd_itempedidos#insere_pedidomisto', via: 'get'
  match '/busca_DetalhesMistos', to: 'fd_pedidomistos#busca_DetalhesMistos', via: 'get'
  match '/lista_pedidos_geral', to: 'static_pedidos#lista_pedidos_geral', via: 'get'
  match '/busca_pedidos_geral', to: 'static_pedidos#busca_pedidos_geral', via: 'get'
  match '/muda_sitaucao_pedido', to: 'static_pedidos#muda_sitaucao_pedido', via: 'get'
  match '/efetua_pagamento', to: 'fd_pedidos#efetua_pagamento', via: 'get'
  match '/busca_caixa_aberto', to: 'fd_caixas#busca_caixa_aberto', via: 'get'
  match '/fechar_caixa', to: 'fd_caixas#fechar_caixa', via: 'get'
  match '/trocarempresa', to: 'fd_usuarios#troca_empresa', via: 'get'
  
  match '/relCaixas', to: 'fd_caixas#relCaixas', via: 'get'

  get '/relPedidosListagem/:fd_caixa_id/', to: 'static_pedidos#relPedidosListagem', as: 'relPedidosListagem'

end

app/models/fd_usuario.rb
#encoding: utf-8
class FdUsuario < ActiveRecord::Base
  belongs_to :fd_empresa

#Presence
	
	validates :desc_nome, :presence => { :message => 'Digite um nome para a pessoa.' }
	validates :desc_login, :presence => { :message => 'Digite o nome de usuário.' }
	validates :desc_confirmalogin, :presence => { :message => 'Digite a confirmação do usuário.' }
	validates :desc_senha, :presence => { :message => 'Digite a senha.' }
	validates :desc_confirmasenha, :presence => { :message => 'Digite a confirmação da senha.' }

#iguality
	validate :check_email_and_confirmation
	validate :check_senha_and_confirmation
	#validate :busca_email_existente


def busca_email_existente
	errors.add(:desc_login, "Usuário já está sendo utilizado.") if FdUsuario.find_by_desc_login(self.desc_login)
end		

def check_email_and_confirmation
  	errors.add(:desc_confirmalogin, "O nome de usuario não foi confirmado corretamente.") if  self.desc_login != self.desc_confirmalogin
end

def check_senha_and_confirmation
  	errors.add(:desc_confirmasenha, "A senha não foi confirmado corretamente.") if self.desc_senha != self.desc_confirmasenha
end


def desc_confirmasenha
  @desc_confirmasenha
end

# setter
def desc_confirmasenha=(val)
  @desc_confirmasenha = val
end 

def desc_confirmalogin
  @desc_confirmalogin
end

# setter
def desc_confirmalogin=(val)
  @desc_confirmalogin = val
end  

end

app/controllers/fd_usuarios_controller.rb
class FdUsuariosController < ApplicationController
  before_action :set_fd_usuario, only: [:show, :edit, :update, :destroy]


def troca_empresa
    fd_usuario = FdUsuario.find(user.id)

    #debugger

    fd_usuario.fd_empresa_id = params[:id]
    fd_usuario.desc_nome = user.desc_nome
    fd_usuario.desc_login = user.desc_login
    fd_usuario.desc_confirmalogin = user.desc_login
    fd_usuario.desc_senha = user.desc_senha
    fd_usuario.desc_confirmasenha = user.desc_senha
    fd_usuario.save

    encerra_sessao

    #redirect_to root_path

end
  # GET /fd_usuarios/1/edit
  def login
    @fd_usuario = FdUsuario.new
  end


  # GET /fd_usuarios
  def index
    @fd_usuarios = FdUsuario.all
  end

  # GET /fd_usuarios/1
  def show
  end

  # GET /fd_usuarios/new
  def new
    @fd_usuario = FdUsuario.new
  end

  # GET /fd_usuarios/1/edit
  def edit

  end

  # POST /fd_usuarios
  def create
    @fd_usuario = FdUsuario.new(fd_usuario_params)

    if @fd_usuario.save
      redirect_to @fd_usuario, notice: 'Registro inserido com sucesso.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /fd_usuarios/1
  def update
    if @fd_usuario.update(fd_usuario_params)
      redirect_to @fd_usuario, notice: 'Registro alterado com sucesso.'
    else
      render action: 'edit'
    end
  end

  # DELETE /fd_usuarios/1
  def destroy
    @fd_usuario.destroy
    redirect_to fd_usuarios_url, notice: 'Registro inserido com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fd_usuario
      @fd_usuario = FdUsuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def fd_usuario_params
      params.require(:fd_usuario).permit(:desc_nome, :desc_login, :desc_senha, :desc_confirmasenha, :desc_confirmalogin, :data_inclusao, :desc_perfil, :fd_empresa_id)
    end
end

app/helpers/fd_usuarios_helper.rb
module FdUsuariosHelper
end

app/views/fd_usuarios/_form.html.erb
<%= form_for(@fd_usuario) do |f| %>
  <% if @fd_usuario.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  
  <% if @fd_usuario.errors.any? %>
  
    <% @fd_usuario.errors.full_messages.each do |msg| %>
        <%= msg %></br>
      <% end %>
     <% end %>
    </div>
  <% end %>   

<div class="row mar-bot40">

  <div class="col-lg-3" >
    <%= f.label :Nome_Completo %><br>
    <%= f.text_field :desc_nome, :class => 'form-control' %>
  </div>
</div>
<br/>
<div class="row mar-bot40">
  <div class="col-lg-3" >
    <%= f.label :Usuario %><br>
    <%= f.text_field :desc_login, :class => 'form-control'  %>
  </div>
</div>
<br/>
<div class="row mar-bot40">
  <div class="col-lg-3" >
    <%= f.label :Confirmação_Usuario %><br>
    <%= f.text_field :desc_confirmalogin, :class => 'form-control'  %>
  </div>
</div>
<br/>
<div class="row mar-bot40">
  <div class="col-lg-3" >
    <%= f.label :Senha %><br>
    <%= f.password_field :desc_senha, :class => 'form-control'  %>
  </div>
</div>
<br/>
<div class="row mar-bot40">
  <div class="col-lg-3" >
    <%= f.label :Confirmação_Senha %><br>
    <%= f.password_field :desc_confirmasenha, :class => 'form-control'  %>
  </div>
</div>

  </div>
</div>

  <!--Capturando usuario logado-->
  <%=f.hidden_field :fd_empresa_id, :value => 3%> 

<hr/>

<div class="btn-group" role="group" aria-label="...">
  <button type="submit" class="btn btn-primary btn-sm">
    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
  </button>  

<% end %>

app/views/fd_usuarios/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editar Usuário</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

<%= render 'form' %>

  <%= link_to @fd_usuario , :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-list-alt"></span> Exibir
  <% end %>

  <%= link_to fd_usuarios_path, :class => "btn btn-default btn-sm" do %>
     <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>  

</div>

app/views/fd_usuarios/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Listar Usuários</h3></div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Login</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fd_usuarios.each do |fd_usuario| %>
      <tr>
        <td><%= fd_usuario.desc_nome %></td>
        <td><%= fd_usuario.desc_login %></td>
          <td align='right'>
            <div class="btn-group">
              <%= link_to fd_usuario, :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-list-alt"></span> Exibir
              <% end %>             
              <%= link_to edit_fd_usuario_path(fd_usuario), :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-pencil"></span> Editar
              <% end %>             
              <%= link_to fd_usuario , :method => :delete,  :confirm => 'Deseja excluir o registro?', :class => "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-trash"></span> Excluir
              <% end %>            
            </div>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to new_fd_usuario_path, :class => "btn btn-default btn-sm" do %>
   <span class="glyphicon glyphicon-file"></span>Novo
<% end %>

app/views/fd_usuarios/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Novo Usuário</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">
<%= render 'form' %>

  <%= link_to fd_usuarios_path, :class => "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>

app/views/fd_usuarios/show.html.erb
<%if notice %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     <%= notice %>
</div>
<%end%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Exibir Usuário</h3>
  </div>
  <div class="panel-footer" style="background-color:white;">

<p>
  <strong>Desc nome:</strong>
  <%= @fd_usuario.desc_nome %>
</p>

<p>
  <strong>Desc login:</strong>
  <%= @fd_usuario.desc_login %>
</p>

<p>
  <strong>Desc senha:</strong>
  <%= @fd_usuario.desc_senha %>
</p>

<p>
  <strong>Data inclusao:</strong>
  <%= @fd_usuario.data_inclusao %>
</p>

<p>
  <strong>Desc perfil:</strong>
  <%= @fd_usuario.desc_perfil %>
</p>

<p>
  <strong>Fd empresas:</strong>
  <%#= @fd_usuario.fd_empresas %>
</p>


  </div>
</div>

<hr/>

<div class="btn-group">          
  <%= link_to edit_fd_usuario_path(@fd_usuario), :class => "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-pencil"></span> Editar
  <% end %>
  <%= link_to fd_empresas_path, :class => "btn btn-default btn-sm" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>       
</div>